#ifndef AOVS_GLSL
#define AOVS_GLSL

// These must match the indices in gi.h
#define AOV_ID_COLOR 0
#define AOV_ID_NORMAL 1
#define AOV_ID_DEBUG_NEE 2
#define AOV_ID_DEBUG_BARYCENTRICS 3
#define AOV_ID_DEBUG_TEXCOORDS 4
#define AOV_ID_DEBUG_BOUNCES 5
#define AOV_ID_DEBUG_CLOCK_CYCLES 6
#define AOV_ID_DEBUG_OPACITY 7
#define AOV_ID_DEBUG_TANGENTS 8
#define AOV_ID_DEBUG_BITANGENTS 9
#define AOV_ID_DEBUG_THIN_WALLED 10
#define AOV_ID_OBJECT_ID 11
#define AOV_ID_DEPTH 12
#define AOV_ID_FACE_ID 13
#define AOV_ID_INSTANCE_ID 14
#define AOV_ID_DEBUG_DOUBLE_SIDED 15

// Mask bits.
#define AOV_BIT_COLOR (1 << 0)
#define AOV_BIT_NORMAL (1 << 1)
#define AOV_BIT_DEBUG_NEE (1 << 2)
#define AOV_BIT_DEBUG_BARYCENTRICS (1 << 3)
#define AOV_BIT_DEBUG_TEXCOORDS (1 << 4)
#define AOV_BIT_DEBUG_BOUNCES (1 << 5)
#define AOV_BIT_DEBUG_CLOCK_CYCLES (1 << 6)
#define AOV_BIT_DEBUG_OPACITY (1 << 7)
#define AOV_BIT_DEBUG_TANGENTS (1 << 8)
#define AOV_BIT_DEBUG_BITANGENTS (1 << 9)
#define AOV_BIT_DEBUG_THIN_WALLED (1 << 10)
#define AOV_BIT_OBJECT_ID (1 << 11)
#define AOV_BIT_DEPTH (1 << 12)
#define AOV_BIT_FACE_ID (1 << 13)
#define AOV_BIT_INSTANCE_ID (1 << 14)
#define AOV_BIT_DEBUG_DOUBLE_SIDED (1 << 15)

#endif
