#ifndef AOVS_GLSL
#define AOVS_GLSL

// These must match the indices in gi.h
#define AOV_ID_COLOR 0
#define AOV_ID_NORMAL 1
#define AOV_ID_DEBUG_NEE 2
#define AOV_ID_DEBUG_BARYCENTRICS 3
#define AOV_ID_DEBUG_TEXCOORDS 4
#define AOV_ID_DEBUG_BOUNCES 5
#define AOV_ID_DEBUG_CLOCK_CYCLES 6
#define AOV_ID_DEBUG_OPACITY 7
#define AOV_ID_DEBUG_TANGENTS 8
#define AOV_ID_DEBUG_BITANGENTS 9
#define AOV_ID_DEBUG_THIN_WALLED 10
#define AOV_ID_OBJECTID 11

// Mask bits.
#define AOV_BIT_COLOR 1
#define AOV_BIT_NORMAL 2
#define AOV_BIT_DEBUG_NEE 4
#define AOV_BIT_DEBUG_BARYCENTRICS 8
#define AOV_BIT_DEBUG_TEXCOORDS 16
#define AOV_BIT_DEBUG_BOUNCES 32
#define AOV_BIT_DEBUG_CLOCK_CYCLES 64
#define AOV_BIT_DEBUG_OPACITY 128
#define AOV_BIT_DEBUG_TANGENTS 256
#define AOV_BIT_DEBUG_BITANGENTS 512
#define AOV_BIT_DEBUG_THIN_WALLED 1024
#define AOV_BIT_OBJECTID 2048

#endif
